### ISSUE TITLE
refactor zone selection to include npctext

### ISSUE THREAD

**Issue by erosson** [mapwatch/mapwatch#125]
When I first designed mapwatch, zone selection was done early in the parsing process, and solely based on the `you have entered` text. This has proven to be a bad assumption; I've had to add many hacks for things that don't fit this approach:

* ~~Parallel campaign zones, ie. act 1 vs act 6 (though this is mostly irrelevant to mapwatch)~~
* [x] "The shaper's realm": shaper vs uber-elder's zones, dependent on shaper's voicelines, #55
* [x] Blighted maps, dependent on cassia's voicelines
* [x] Heist blueprints vs heist contracts, #120
* [x] Laboratory map vs laboratory heist contract, #124
* ~~Heist boss in "the den" vs the campaign zone, #119~~
* [x] Labyrinth detection #208
* Others I've forgotten?

Zone selection must properly include npctext. Right now we include npctext in a bunch of different hacky places between parsing and the view, but it'd save a lot of trouble for it to be done properly during parsing.

**Comment by erosson** [comment]
I'm moving all of these to MapRun.elm, as results of parsing RawMapRun.
