### ISSUE TITLE
3.17 stuff

### ISSUE THREAD

**Issue by erosson** [mapwatch/mapwatch#348]
* [x] no show-league-maps button (#394)
* [x] mapwatch build is broken (#394)
  * this has been too fragile. needs some redesigns long-term. smaller jobs?
* [x] kill map regions
* [x] maps didn't register (#394)
  * bone crypt
  * grave trough
* new boss fights
  * [x] black star, infinite hunger
  * [x] searing exarch, eater of worlds
* ritual reminders still work 🙌  market them better?
* [x] examine logs and confirm: can't detect archnemesis, right?
