### ISSUE TITLE
finish bosskill-tracking page

### ISSUE THREAD

**Issue by erosson** [mapwatch/mapwatch#432]
https://mapwatch.erosson.org/?example=siege-eater-exarch.txt#/bosses

from #416. there are no links to this page yet

* [ ] add uber bosses to test data
* [ ] basic achievements ui
* [ ] sort and filter achievements
* [ ] achievement-unlocked speech notifications
* [ ] collapsible shaper guardians, lesser conquerors
* [ ] distinguish boss-start time from map-start time, for logoutless conquerors (low priority)
* [ ] finally, add incoming nav link, and launch
